(function(){
'use strict';
var DATA={
who:[['Knight','Brave and sturdy; good when danger needs facing head-on.'],['Witch','Understands magic, curses and supernatural things.'],['Robot','Brilliant with machines and difficult to frighten.'],['Goblin','Crafty and excellent at getting into places.'],['Explorer','Navigates, improvises and spots useful routes.'],['Bard','Performs, persuades and redirects attention.']],
weird:[['Tiny','Can squeeze through spaces nobody else can.'],['Haunted','A helpful-ish ghost follows you and understands spooky things.'],['Elastic','Can stretch to reach improbable places.'],['Invisible','Can disappear from sight when it matters.'],['Extremely Loud','Can make enough noise to distract almost anything.'],['Magnetic','Metal objects have a habit of flying toward you.'],['Two-Headed','Can watch and think about two things at once.'],['Ridiculously Tall','High shelves, walls and windows are much less impressive.']],
talent:[['Befriend','Turns creatures and strangers into allies.'],['Smash','Breaks, forces or batters uncooperative things.'],['Sneak','Moves quietly and avoids unwanted attention.'],['Fix','Repairs, rewires or bodges broken things into usefulness.'],['Climb','Finds a way upward whenever one exists.'],['Distract','Makes someone look anywhere except where they should.'],['Track','Follows trails, signs and clues others miss.'],['Perform','Entertains, calms nerves or creates a spectacle.']],
power:[['Teleport','Instantly reach somewhere otherwise inaccessible.'],['Freeze','Stop a creature, object or hazard for one crucial moment.'],['Copy','Imitate another hero’s ready non-Power capability.'],['Transform','Become a useful creature or shape for one problem.'],['Shield','Protect the whole team from one dangerous consequence.'],['Reverse','Make one moving, flowing or falling thing go the other way.'],['Grow','Become enormous until the current problem is resolved.'],['Time Skip','Skip past one immediate obstacle.']],
items:[['A Very Long Rope','Useful for climbing, lowering, tying or pulling.'],['Suspicious Magnet','Powerful enough to move inconvenient metal.'],['Enormous Umbrella','Useful against weather, falling things and maybe gliding.'],['Convincing Disguise','At a distance, you definitely belong here.'],['Shiny Mirror','Reflects light and is excellent for signalling.'],['Jar of Sticky Goo','Sticks two things together far too firmly.']],
enc:[
['The Key Above the Door','Straight problem','The iron door is locked. Its key hangs from a hook far above your heads.','Find a convincing way to get the key down.','Elastic, Ridiculously Tall, Climb, Teleport, Grow, a rope, Magnetic, or another convincing reach solution.',1],
['The Sleeping Ogre','Choose a route','An enormous ogre is asleep across the only path. Every snore shakes dust from the ceiling.','Slip past, distract it, move it, befriend it or find another route.','Invisible or Sneak can pass quietly. Extremely Loud, Distract, Bard or Perform can redirect it. Befriend may work. Teleport bypasses it.',1],
['The Stuck Portcullis','Team combination','A heavy gate has jammed halfway up. The release lever is beyond a narrow gap.','Use one hero to deal with the gate and another to reach the lever.','Smash, Grow or Knight can hold/lift it while Tiny, Elastic, Goblin or Teleport reaches the lever. Two contributions are intended.',2],
['The Endless Staircase','Conserve or pay','The staircase winds upward and upward. You could spend something clever or simply endure it.','Spend a useful capability, or save everything and take the setback.','Teleport, Grow, Elastic, Explorer, Climb or another convincing shortcut.',1],
['The Abandoned Workshop','Reward opportunity','A strange machine hums in the corner. Something useful rattles inside it.','Safely understand, open or dismantle it to gain an item.','Robot, Fix, Witch, Tiny, Magnetic, or perhaps Smash with a less delicate approach.',0,'item'],
['The Quiet Clearing','Recovery opportunity','For once, nothing is chasing you. A sheltered clearing looks almost safe.','Make camp genuinely safe to refresh one spent non-Power capability.','Explorer, Track, Befriend local creatures, Shield, Fix a shelter, Knight standing guard, or another safety plan.',0,'recover'],
['Something Is Following You','Escalating problem','Branches snap behind you. Whatever is back there is getting closer.','Deal with the follower now, or carry the problem with you.','Track, Befriend, Invisible, Sneak, Extremely Loud, Perform, Freeze, Teleport, or another convincing plan.',0,'followed'],
['The Broken Rope Bridge','Choose a route','The bridge has collapsed into the gorge. One frayed rope still reaches the far side.','Reach the far side, improvise a crossing, or force your way through at a cost.','Elastic, Climb, Teleport, Grow, Robot/Fix, a suitable item or another plausible crossing.',1,'rope'],
['A Very Lonely Dragon','Reward opportunity','The dragon blocks the tunnel. Oddly, it does not look angry. It looks bored.','Get past it — or make a friend and gain something useful.','Befriend, Bard, Perform, Witch, Haunted, Extremely Loud used entertainingly, a gift, or another social solution.',1,'item'],
['The Room Filling With Jelly','Conserve or pay','Purple jelly pours through cracks in the walls. It is already up to your knees.','Stop the flow, escape quickly, or accept the messy consequences.','Freeze, Fix, Smash an exit, Tiny, Teleport, Grow, Shield, Elastic, or a clever item.',2],
['The Upside-Down Hallway','Team combination','Gravity has decided the ceiling is now the floor. The exit is twenty feet above you.','Get the whole team to the new floor. Combining two heroes may be easiest.','Climb, Elastic, Grow, Teleport, Witch, Robot/Fix, rope plus a suitable hero, or two complementary capabilities.',1],
['The Nervous Ghost','Recovery opportunity','A translucent figure blocks the corridor, apologising repeatedly. It seems terrified of you.','Help the ghost calm down or understand what it wants.','Haunted, Witch, Befriend, Bard, Perform, Two-Headed listening patiently, or another kind solution.',1,'recover']
],
fin:[
['The Clockwork Beast','A gigantic clockwork creature wakes. Gears spin and the floor tilts toward a furnace.',[['Stop the room itself becoming impossible to stand in.','Fix, Robot, Freeze, Reverse, Grow, Shield or another control solution.'],['Reach the creature’s glowing control panel.','Elastic, Climb, Tiny, Teleport, Ridiculously Tall, Grow, rope or teamwork.'],['Shut it down without losing the whole team.','Robot/Fix, Witch, Smash, Freeze, Shield, Copy, an item or a convincing combination.']]],
['The Castle Wakes Up','The entire castle stretches, yawns and begins walking away on enormous stone legs.',[['Keep the team together while the rooms rearrange.','Explorer, Track, Elastic, Extremely Loud, Two-Headed, Shield or teamwork.'],['Reach the control bell outside the highest tower.','Climb, Elastic, Ridiculously Tall, Grow, Teleport, rope or a creative route.'],['Convince, force or trick the castle into sitting down.','Witch, Bard, Perform, Smash, Robot/Fix, Befriend creatively, Reverse or a combination.']]]
]};
var KEY='oddventurers-v3', state={screen:'home'};
function load(){try{var r=localStorage.getItem(KEY);if(r)state=JSON.parse(r);}catch(e){state={screen:'home'};}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}}
function shuffle(a){return a.slice().sort(function(){return Math.random()-.5;});}
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function e(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function go(){save();render();}
window.resetGame=function(){try{localStorage.removeItem(KEY);}catch(e){} state={screen:'home'};render();};
window.newGame=function(n){state={screen:'build',players:n,b:0,heroes:[],draft:{},trouble:0,items:[],conditions:[],idx:0,fs:0};for(var i=0;i<n;i++)state.heroes.push({name:'Hero '+(i+1),modules:{},spent:{}});makeDraft();go();};
function makeDraft(){state.draft={};['who','weird','talent','power'].forEach(function(k){state.draft[k]=shuffle(DATA[k]).slice(0,2);});}
window.choose=function(k,name){var arr=DATA[k],found=null;for(var i=0;i<arr.length;i++)if(arr[i][0]===name)found=arr[i];state.heroes[state.b].modules[k]={name:found[0],desc:found[1]};go();};
function built(){return ['who','weird','talent','power'].every(function(k){return !!state.heroes[state.b].modules[k];});}
window.nextHero=function(){if(!built())return;if(state.b<state.players-1){state.b++;makeDraft();}else{state.adventure=shuffle(DATA.enc).slice(0,8);state.finale=pick(DATA.fin);state.screen='adventure';state.idx=0;state.fs=0;}go();};
window.spend=function(i,k){state.heroes[i].spent[k]=!state.heroes[i].spent[k];go();};
window.useItem=function(i){state.items.splice(i,1);go();};
function addItem(kind){var x=kind==='rope'?DATA.items[0]:pick(DATA.items);state.items.push(x);}
function advance(){state.idx++;if(state.idx>=state.adventure.length)state.screen='finale';go();}
window.solved=function(){var x=state.adventure[state.idx][6];if(x==='item'||x==='rope')addItem(x);if(x==='recover'){state.screen='recover';go();}else advance();};
window.failed=function(){var q=state.adventure[state.idx];if(q[6]==='followed'&&state.conditions.indexOf('Followed')<0)state.conditions.push('Followed');state.trouble+=q[5]||0;if(state.trouble>=5){state.screen='lost';go();}else advance();};
window.recoverOne=function(i,k){state.heroes[i].spent[k]=false;state.screen='adventure';advance();};
window.finalStep=function(fail){if(fail)state.trouble+=2;if(state.trouble>=5){state.screen='lost';go();return;}state.fs++;if(state.fs>=3)state.screen='won';go();};
window.toggleRef=function(id){var x=document.getElementById(id);if(x)x.classList.toggle('hidden');};
function top(extra){return '<div class="top"><div><div class="brand">Oddventurers</div><div class="small">prototype v0.3 '+(extra||'')+'</div></div><button class="btn secondary" onclick="resetGame()">New game</button></div>';}
function hero(h,i,live){var s='<div class="card hero"><h3>'+e(h.name)+(h.modules.who?' — '+e(h.modules.who.name):'')+'</h3>';['who','weird','talent','power'].forEach(function(k){var m=h.modules[k];if(!m)return;s+='<button '+(live?'':'disabled')+' class="module '+(h.spent[k]?'spent':'')+'" onclick="spend('+i+',\''+k+'\')"><div class="type">'+k+' • '+(h.spent[k]?'SPENT':'READY')+'</div><div class="title">'+e(m.name)+'</div><p>'+e(m.desc)+'</p></button>';});return s+'</div>';}
function team(){var s='<details class="card"><summary><b>Show team capabilities</b></summary><div class="heroes">';state.heroes.forEach(function(h,i){s+=hero(h,i,true);});s+='</div></details><div class="card"><h3>Shared items</h3>';if(!state.items.length)s+='<p class="muted">Nothing useful yet.</p>';else state.items.forEach(function(x,i){s+='<div class="item"><b>'+e(x[0])+'</b><div class="small">'+e(x[1])+'</div><button class="btn secondary" onclick="useItem('+i+')">Use / discard</button></div>';});return s+'</div>';}
function meter(){var s='<div class="row"><b>Team Trouble</b><span>'+state.trouble+'/5</span></div><div class="trouble">';for(var i=0;i<5;i++)s+='<i class="'+(i<state.trouble?'on':'')+'"></i>';return s+'</div>';}
function reference(text,id){return '<button class="btn secondary" style="width:100%" onclick="toggleRef(\''+id+'\')">Check intended solutions</button><div id="'+id+'" class="ref hidden"><b>Reference:</b><br>'+e(text)+'<hr>This is guidance, not a whitelist. If your idea clearly makes sense, use it.</div>';}
function home(){return '<div class="shell">'+top('')+'<div class="card"><h1>Build something ridiculous.</h1><p class="story">Make weird heroes, then ration their strange capabilities through an unknown cooperative adventure.</p></div><div class="card"><h2>How many heroes?</h2><div class="grid2"><button class="btn" onclick="newGame(2)">2 heroes</button><button class="btn" onclick="newGame(3)">3 heroes</button><button class="btn" onclick="newGame(4)">4 heroes</button><button class="btn secondary" onclick="newGame(1)">Solo test</button></div></div><div class="card"><b>Core rule:</b> propose a capability that could genuinely solve the problem. Spend it by tapping the capability, or keep it ready and accept the setback.</div></div>';}
function build(){var h=state.heroes[state.b],out='<div class="shell">'+top('• build '+(state.b+1)+'/'+state.players)+'<div class="card"><h1>Make Hero '+(state.b+1)+'</h1><p>Choose one from each pair.</p></div>';['who','weird','talent','power'].forEach(function(k){var labels={who:'Who are you?',weird:'What’s unusual about you?',talent:'What are you good at?',power:'What impossible thing can you do?'};out+='<div class="card"><h3>'+labels[k]+'</h3><div class="grid2">';state.draft[k].forEach(function(x){var sel=h.modules[k]&&h.modules[k].name===x[0];out+='<button class="module '+(sel?'selected':'')+'" onclick="choose(\''+k+'\',\''+e(x[0])+'\')"><div class="title">'+e(x[0])+'</div><p>'+e(x[1])+'</p></button>';});out+='</div></div>';});out+='<div class="bottom"><div><span></span><button class="btn good" '+(built()?'':'disabled')+' onclick="nextHero()">'+(state.b===state.players-1?'Start adventure':'Next hero')+'</button></div></div></div>';return out;}
function adventure(){var q=state.adventure[state.idx],id='ref'+state.idx;return '<div class="shell">'+top('• encounter '+(state.idx+1)+'/8')+meter()+(state.conditions.length?'<div class="card"><b>Complication:</b> '+e(state.conditions.join(', '))+'</div>':'')+'<div class="card encounter"><div class="tag">'+e(q[1])+'</div><h1>'+e(q[0])+'</h1><p class="story">'+e(q[2])+'</p><p><b>What do you do?</b><br>'+e(q[3])+'</p>'+reference(q[4],id)+'</div>'+team()+'<div class="bottom"><div><button class="btn good" onclick="solved()">We solved it</button><button class="btn bad" onclick="failed()">Take setback'+(q[5]?' +'+q[5]+' Trouble':'')+'</button></div></div></div>';}
function recovery(){var choices=[];state.heroes.forEach(function(h,i){['who','weird','talent'].forEach(function(k){if(h.spent[k])choices.push([i,k,h.modules[k]]);});});if(!choices.length){state.screen='adventure';advance();return '';}var s='<div class="shell">'+top('')+'<div class="card"><h1>Catch your breath</h1><p>Refresh one spent non-Power capability.</p></div>';choices.forEach(function(x){s+='<button class="module" onclick="recoverOne('+x[0]+',\''+x[1]+'\')"><div class="title">'+e(state.heroes[x[0]].name)+': '+e(x[2].name)+'</div><p>'+e(x[2].desc)+'</p></button>';});return s+'</div>';}
function finale(){var f=state.finale,st=f[2][state.fs];return '<div class="shell">'+top('• finale '+(state.fs+1)+'/3')+meter()+'<div class="card encounter"><div class="tag">Finale</div><h1>'+e(f[0])+'</h1>'+(state.fs===0?'<p class="story">'+e(f[1])+'</p>':'')+'<p><b>Stage '+(state.fs+1)+'</b><br>'+e(st[0])+'</p>'+reference(st[1],'fref')+'</div>'+team()+'<div class="bottom"><div><button class="btn good" onclick="finalStep(false)">Solved</button><button class="btn bad" onclick="finalStep(true)">Fail: +2 Trouble</button></div></div></div>';}
function end(win){return '<div class="shell">'+top('')+'<div class="card"><h1>'+(win?'You made it!':'The adventure got you.')+'</h1><p class="story">'+(win?'Your deeply questionable heroes somehow survived. What completely different characters do you want to build next?':'Rebuild the team and see whether a stranger combination does better.')+'</p><button class="btn good" onclick="resetGame()">Build another team</button></div></div>';}
function render(){var app=document.getElementById('app');if(!app)return;try{if(state.screen==='home')app.innerHTML=home();else if(state.screen==='build')app.innerHTML=build();else if(state.screen==='adventure')app.innerHTML=adventure();else if(state.screen==='recover')app.innerHTML=recovery();else if(state.screen==='finale')app.innerHTML=finale();else if(state.screen==='won')app.innerHTML=end(true);else app.innerHTML=end(false);}catch(err){app.innerHTML='<div class="shell"><div class="card"><h1>Oddventurers</h1><p>Game error: '+e(err.message)+'</p><button class="btn good" onclick="resetGame()">Reset game</button></div></div>';}}
load();render();
})();
